pipeline {
    agent any

 tools {
        maven 'maven-3.9.6' // Adjust the Maven version as per your installation
        jdk 'jdk-17' // Adjust the JDK version as per your installation
     }

    environment {
      SPRINGBOOT_REPO = 'https://github.com/subhashis2018/springboot_cicd_1.git'
    }

    stages {
        stage('Checkout') {
            steps {
                git branch: 'main', url: "${SPRINGBOOT_REPO}", credentialsId: 'github-credentials'
            }
        }
         stage('Maven Clean') {
            steps {
                // export JAVA_HOME=/usr/lib/jvm/jdk-17-oracle-x64
                // export MVN_HOME=/usr/share/maven
                // export PATH=$JAVA_HOME/bin:$MVN_HOME/bin:$PATH
                sh 'mvn clean'
            }
        }

        stage('Maven Build') {
            steps {
                sh 'mvn package'
            }
        }
        
    }
}